spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:h2:mem:shedlock_DB;INIT=CREATE SCHEMA IF NOT EXISTS shedlock;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: postgres
    password: 1mperator
  cloud:
    openfeign:
      client:
        config:
          cheque:
            url: http://localhost:7070/api/paying
            connect-timeout: 1_200_000
            read-timeout: 1_200_000